apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/danilo-gemoli/foobar?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: foobar
    appstudio.openshift.io/component: foobar
    pipelines.appstudio.openshift.io/type: build
  name: foobar-on-pull-request
  namespace: rh-ee-dgemoli-tenant

spec:
  pipelineSpec:
    description: Provision ephemeral cluster test

    tasks:
    - name: provision-ephemeral-cluster
      params:
      - name: workflow
        value: generic-claim
      - name: clusterClaim
        value: |
          {
            "architecture": "amd64",
            "as": "unused",
            "cloud": "aws",
            "labels": {
              "region": "us-east-1"
            },
            "owner": "openshift-ci",
            "product": "ocp",
            "timeout": "1h0m0s",
            "version": "4.19"
          }
      - name: ownerName
        value: $(context.pipelineRun.name)
      - name: ownerUid
        value: $(context.pipelineRun.uid)
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/openshift/konflux-tasks
        - name: revision
          value: main
        - name: pathInRepo
          value: tasks/provision-ephemeral-cluster/0.1/provision-ephemeral-cluster.yaml

    - name: run-test
      runAfter:
      - provision-ephemeral-cluster
      params:
      - name: clusterCredentialsSecretRef
        value: $(tasks.provision-ephemeral-cluster.results.secretRef)
      taskSpec:
        params:
        - name: clusterCredentialsSecretRef
          type: string
          description: "The secret that holds the cluster credentials"
        steps:
        - name: run-test
          image: registry.redhat.io/openshift4/ose-cli:4.13@sha256:73df37794ffff7de1101016c23dc623e4990810390ebdabcbbfa065214352c7c
          env:
          - name: KUBECONFIG_VALUE
            valueFrom:
              secretKeyRef:
                name: $(params.clusterCredentialsSecretRef)
                key: kubeconfig
          - name: ADMIN_PASSWD
            valueFrom:
              secretKeyRef:
                name: $(params.clusterCredentialsSecretRef)
                key: kubeAdminPassword
          script: |
            #!/usr/bin/env bash
            set -eo pipefail

            KUBECONFIG="$(mktemp kubeconfig.XXXXX)"
            trap 'rm -f "$KUBECONFIG"' EXIT

            echo "$KUBECONFIG_VALUE" >"$KUBECONFIG"
            export KUBECONFIG
            oc whoami

            kk="$KUBECONFIG"
            unset KUBECONFIG

            endpoint="$(yq '.clusters[0].cluster.server' $kk | sed 's|https://||g')"
            printf 'endpoint: %s\n' "$endpoint"

            oc login --insecure-skip-tls-verify -u kubeadmin -p "$(cat passwd)" "$endpoint"
            oc whoami

    finally:
    - name: deprovision-ephemeral-cluster
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/openshift/konflux-tasks
        - name: revision
          value: main
        - name: pathInRepo
          value: tasks/deprovision-ephemeral-cluster/0.1/deprovision-ephemeral-cluster.yaml
      params:
      - name: testPlatformClusterClaimName
        value: $(tasks.provision-ephemeral-cluster.results.testPlatformClusterClaimName)
      - name: testPlatformClusterClaimNamespace
        value: $(tasks.provision-ephemeral-cluster.results.testPlatformClusterClaimNamespace)

  taskRunTemplate:
    serviceAccountName: build-pipeline-foobar

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  timeouts:
    pipeline: 12h0m0s
    tasks: 6h0m0s
    finally: 6h0m0s

status: {}
