apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/danilo-gemoli/foobar?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "staging"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: foobar
    appstudio.openshift.io/component: foobar
    pipelines.appstudio.openshift.io/type: build
  name: foobar-on-pull-request-stg
  namespace: testplatform-ci-tenant
spec:
  pipelineSpec:
    description: dummy
    tasks:
    - name: dump-variables
      taskSpec:
        steps:
        - name: dump-variables
          image: registry.redhat.io/openshift4/ose-cli:4.13@sha256:73df37794ffff7de1101016c23dc623e4990810390ebdabcbbfa065214352c7c 
          script: |
            #!/bin/bash
            set -eo pipefail
            echo "---"
            echo "taskRun name: $(context.taskRun.name)"
            echo "---"
            echo "taskRun NS: $(context.taskRun.namespace)"
            echo "---"
            echo "taskRun uid: $(context.taskRun.uid)"
            echo "---"
  taskRunTemplate:
    serviceAccountName: build-pipeline-foobar
status: {}
